import 'package:oneship_customer/core/base/base_import_components.dart';

enum ErrorCodeEnum {
  auth001,
  auth002,
  auth003,
  auth004,
  auth005,
  auth006,
  auth007,
  auth008,
  auth009,
  auth010,
  auth011,
  auth012,
  auth013,
  auth014,
  auth015,
  auth021,
  auth023,

  address001,
  address002,
  address003,
  address004,
  address005,

  validation002,

  order001,
  order002,
  order003,
  order004,
  order005,
  order006,
  order024,

  package001,
  package002,
  package003,
  package004,
  package006,
  package007,
  package008,
  package009,
  package010,
  package011,
  package012,
  package013,
  package014,
  package015,
  package016,
  package017,
  package019,
  package020,
  package060,
  package061,

  review001,
  review002,
  review003,
  review004,
  review005,
  review006,

  shipper001,
  shipper002,
  shipper003,
  shipper004,
  shipper005,
  shipper006,
  shipper007,
  shipper008,
  shipper009,
  shipper010,
  shipper020,
  shipper022,

  statistics001,
  statistics002,
  statistics003,

  user001,
  user002,
  user003,
  user004,
  user005,
  user006,
  user007,
  user008,
  user009,
  user010,
  user011,
  user012,
  user013,
  user014,
  user015,

  paymentCard01,
  paymentCard02,
  paymentCard03,
  paymentCard04,
  paymentCard05,
  paymentCard06,
  paymentCard07,
  paymentCard08,
  paymentCard09,

  userDoc001,
  userDoc002,
  userDoc003,
  userDoc004,
  userDoc005,

  wallet001,
  wallet002,
  wallet003,
  wallet004,
  wallet005,
  wallet006,
  wallet007,

  unknown,
}

extension ErrorCodeEnumExt on ErrorCodeEnum {
  static const _mapKey = {
    ErrorCodeEnum.auth001: 'AUTH_001',
    ErrorCodeEnum.auth002: 'AUTH_002',
    ErrorCodeEnum.auth003: 'AUTH_003',
    ErrorCodeEnum.auth004: 'AUTH_004',
    ErrorCodeEnum.auth005: 'AUTH_005',
    ErrorCodeEnum.auth006: 'AUTH_006',
    ErrorCodeEnum.auth007: 'AUTH_007',
    ErrorCodeEnum.auth008: 'AUTH_008',
    ErrorCodeEnum.auth009: 'AUTH_009',
    ErrorCodeEnum.auth010: 'AUTH_010',
    ErrorCodeEnum.auth011: 'AUTH_011',
    ErrorCodeEnum.auth012: 'AUTH_012',
    ErrorCodeEnum.auth013: 'AUTH_013',
    ErrorCodeEnum.auth014: 'AUTH_014',
    ErrorCodeEnum.auth015: 'AUTH_015',
    ErrorCodeEnum.auth021: 'AUTH_021',
    ErrorCodeEnum.auth023: 'AUTH_023',

    ErrorCodeEnum.address001: 'ADDRESS_001',
    ErrorCodeEnum.address002: 'ADDRESS_002',
    ErrorCodeEnum.address003: 'ADDRESS_003',
    ErrorCodeEnum.address004: 'ADDRESS_004',
    ErrorCodeEnum.address005: 'ADDRESS_005',

    ErrorCodeEnum.validation002: 'VALIDATION_002',

    ErrorCodeEnum.order001: 'ORDER_001',
    ErrorCodeEnum.order002: 'ORDER_002',
    ErrorCodeEnum.order003: 'ORDER_003',
    ErrorCodeEnum.order004: 'ORDER_004',
    ErrorCodeEnum.order005: 'ORDER_005',
    ErrorCodeEnum.order006: 'ORDER_006',
    ErrorCodeEnum.order024: 'ORDER_024',

    ErrorCodeEnum.package001: 'PACKAGE_001',
    ErrorCodeEnum.package002: 'PACKAGE_002',
    ErrorCodeEnum.package003: 'PACKAGE_003',
    ErrorCodeEnum.package004: 'PACKAGE_004',
    ErrorCodeEnum.package006: 'PACKAGE_006',
    ErrorCodeEnum.package007: 'PACKAGE_007',
    ErrorCodeEnum.package008: 'PACKAGE_008',
    ErrorCodeEnum.package009: 'PACKAGE_009',
    ErrorCodeEnum.package010: 'PACKAGE_010',
    ErrorCodeEnum.package011: 'PACKAGE_011',
    ErrorCodeEnum.package012: 'PACKAGE_012',
    ErrorCodeEnum.package013: 'PACKAGE_013',
    ErrorCodeEnum.package014: 'PACKAGE_014',
    ErrorCodeEnum.package015: 'PACKAGE_015',
    ErrorCodeEnum.package016: 'PACKAGE_016',
    ErrorCodeEnum.package017: 'PACKAGE_017',
    ErrorCodeEnum.package019: 'PACKAGE_019',
    ErrorCodeEnum.package020: 'PACKAGE_020',
    ErrorCodeEnum.package060: 'PACKAGE_060',
    ErrorCodeEnum.package061: 'PACKAGE_061',

    ErrorCodeEnum.review001: 'REVIEW_001',
    ErrorCodeEnum.review002: 'REVIEW_002',
    ErrorCodeEnum.review003: 'REVIEW_003',
    ErrorCodeEnum.review004: 'REVIEW_004',
    ErrorCodeEnum.review005: 'REVIEW_005',
    ErrorCodeEnum.review006: 'REVIEW_006',

    ErrorCodeEnum.shipper001: 'SHIPPER_001',
    ErrorCodeEnum.shipper002: 'SHIPPER_002',
    ErrorCodeEnum.shipper003: 'SHIPPER_003',
    ErrorCodeEnum.shipper004: 'SHIPPER_004',
    ErrorCodeEnum.shipper005: 'SHIPPER_005',
    ErrorCodeEnum.shipper006: 'SHIPPER_006',
    ErrorCodeEnum.shipper007: 'SHIPPER_007',
    ErrorCodeEnum.shipper008: 'SHIPPER_008',
    ErrorCodeEnum.shipper009: 'SHIPPER_009',
    ErrorCodeEnum.shipper010: 'SHIPPER_010',
    ErrorCodeEnum.shipper020: 'SHIPPER_020',
    ErrorCodeEnum.shipper022: 'SHIPPER_022',

    ErrorCodeEnum.statistics001: 'STATISTICS_001',
    ErrorCodeEnum.statistics002: 'STATISTICS_002',
    ErrorCodeEnum.statistics003: 'STATISTICS_003',

    ErrorCodeEnum.user001: 'USER_001',
    ErrorCodeEnum.user002: 'USER_002',
    ErrorCodeEnum.user003: 'USER_003',
    ErrorCodeEnum.user004: 'USER_004',
    ErrorCodeEnum.user005: 'USER_005',
    ErrorCodeEnum.user006: 'USER_006',
    ErrorCodeEnum.user007: 'USER_007',
    ErrorCodeEnum.user008: 'USER_008',
    ErrorCodeEnum.user009: 'USER_009',
    ErrorCodeEnum.user010: 'USER_010',
    ErrorCodeEnum.user011: 'USER_011',
    ErrorCodeEnum.user012: 'USER_012',
    ErrorCodeEnum.user013: 'USER_013',
    ErrorCodeEnum.user014: 'USER_014',
    ErrorCodeEnum.user015: 'USER_015',

    ErrorCodeEnum.paymentCard01: 'PAYMENT_CARD_01',
    ErrorCodeEnum.paymentCard02: 'PAYMENT_CARD_02',
    ErrorCodeEnum.paymentCard03: 'PAYMENT_CARD_03',
    ErrorCodeEnum.paymentCard04: 'PAYMENT_CARD_04',
    ErrorCodeEnum.paymentCard05: 'PAYMENT_CARD_05',
    ErrorCodeEnum.paymentCard06: 'PAYMENT_CARD_06',
    ErrorCodeEnum.paymentCard07: 'PAYMENT_CARD_07',
    ErrorCodeEnum.paymentCard08: 'PAYMENT_CARD_08',
    ErrorCodeEnum.paymentCard09: 'PAYMENT_CARD_09',

    ErrorCodeEnum.userDoc001: 'USER_DOC_001',
    ErrorCodeEnum.userDoc002: 'USER_DOC_002',
    ErrorCodeEnum.userDoc003: 'USER_DOC_003',
    ErrorCodeEnum.userDoc004: 'USER_DOC_004',
    ErrorCodeEnum.userDoc005: 'USER_DOC_005',

    ErrorCodeEnum.wallet001: 'WALLET_001',
    ErrorCodeEnum.wallet002: 'WALLET_002',
    ErrorCodeEnum.wallet003: 'WALLET_003',
    ErrorCodeEnum.wallet004: 'WALLET_004',
    ErrorCodeEnum.wallet005: 'WALLET_005',
    ErrorCodeEnum.wallet006: 'WALLET_006',
    ErrorCodeEnum.wallet007: 'WALLET_007',

    ErrorCodeEnum.unknown: '',
  };

  static const _mapValue = {
    // AUTH
    ErrorCodeEnum.auth001: 'error_code.auth.user_not_found',
    ErrorCodeEnum.auth002: 'error_code.auth.invalid_credentials',
    ErrorCodeEnum.auth003: 'error_code.auth.user_already_exists',
    ErrorCodeEnum.auth004: 'error_code.auth.account_locked',
    ErrorCodeEnum.auth005: 'error_code.auth.token_expired',
    ErrorCodeEnum.auth006: 'error_code.auth.token_invalid',
    ErrorCodeEnum.auth007: 'error_code.auth.token_not_found',
    ErrorCodeEnum.auth008: 'error_code.auth.authentication_required',
    ErrorCodeEnum.auth009: 'error_code.auth.access_denied',
    ErrorCodeEnum.auth010: 'error_code.auth.session_revoked',
    ErrorCodeEnum.auth011: 'error_code.auth.otp_invalid_or_expired',
    ErrorCodeEnum.auth012: 'error_code.auth.otp_request_cooldown',
    ErrorCodeEnum.auth013: 'error_code.auth.user_locked',
    ErrorCodeEnum.auth014: 'error_code.auth.otp_invalid',
    ErrorCodeEnum.auth015: 'error_code.auth.phone_invalid',
    ErrorCodeEnum.auth021: 'error_code.auth.user_duplicate_log_in',
    ErrorCodeEnum.auth023: 'error_code.auth.rejection_lock',

    // ADDRESS
    ErrorCodeEnum.address001: 'error_code.address.province_not_found',
    ErrorCodeEnum.address002: 'error_code.address.ward_not_found',
    ErrorCodeEnum.address003: 'error_code.address.not_found',
    ErrorCodeEnum.address004: 'error_code.address.invalid_coordinates',
    ErrorCodeEnum.address005: 'error_code.address.access_denied',

    // VALIDATION
    ErrorCodeEnum.validation002: 'error_code.validate.invalid_vn_phone_number',

    // ORDER
    ErrorCodeEnum.order001: 'error_code.order.not_found',
    ErrorCodeEnum.order002: 'error_code.order.date_range_too_large',
    ErrorCodeEnum.order003: 'error_code.order.access_denied',
    ErrorCodeEnum.order004: 'error_code.order.terms_not_accepted',
    ErrorCodeEnum.order005: 'error_code.order.deletion_not_allowed',
    ErrorCodeEnum.order006: 'error_code.order.shop_inactive',
    ErrorCodeEnum.order024: 'error_code.order.order_must_be_in_shipping',

    // PACKAGE
    ErrorCodeEnum.package001: 'error_code.package.not_found',
    ErrorCodeEnum.package002: 'error_code.package.data_not_found',
    ErrorCodeEnum.package003: 'error_code.package.assignment_not_found',
    ErrorCodeEnum.package004: 'error_code.package.already_picked_up',
    ErrorCodeEnum.package006: 'error_code.package.being_processed',
    ErrorCodeEnum.package007: 'error_code.package.shop_coordinates_required',
    ErrorCodeEnum.package008: 'error_code.package.tsp_route_failed',
    ErrorCodeEnum.package009: 'error_code.package.no_available_shippers',
    ErrorCodeEnum.package010: 'error_code.package.vietmap_failed',
    ErrorCodeEnum.package011: 'error_code.package.invalid_tsp_data',
    ErrorCodeEnum.package012: 'error_code.package.order_sequence_not_found',
    ErrorCodeEnum.package013: 'error_code.package.no_valid_orders',
    ErrorCodeEnum.package014: 'error_code.package.split_failed',
    ErrorCodeEnum.package015: 'error_code.package.timeout_expired',
    ErrorCodeEnum.package016: 'error_code.package.tracking_code_not_in_package',
    ErrorCodeEnum.package017: 'error_code.package.not_all_orders_scanned',
    ErrorCodeEnum.package019: 'error_code.package.merged_conflict',
    ErrorCodeEnum.package020: 'error_code.package.shop_not_found',
    ErrorCodeEnum.package060:
        'error_code.package.shipper_too_far_from_delivery',
    ErrorCodeEnum.package061:
        'error_code.package.shipper_too_far_from_delivery',

    // REVIEW
    ErrorCodeEnum.review001: 'error_code.review.not_found',
    ErrorCodeEnum.review002: 'error_code.review.reply_not_found',
    ErrorCodeEnum.review003: 'error_code.review.duplicate',
    ErrorCodeEnum.review004: 'error_code.review.invalid_rating',
    ErrorCodeEnum.review005: 'error_code.review.unauthorized_access',
    ErrorCodeEnum.review006: 'error_code.review.invalid_reference',

    // SHIPPER
    ErrorCodeEnum.shipper001: 'error_code.shipper.not_found',
    ErrorCodeEnum.shipper002: 'error_code.shipper.user_not_shipper',
    ErrorCodeEnum.shipper003: 'error_code.shipper.coordinates_update_failed',
    ErrorCodeEnum.shipper004: 'error_code.shipper.already_exists',
    ErrorCodeEnum.shipper005: 'error_code.shipper.user_not_authorized',
    ErrorCodeEnum.shipper006:
        'error_code.shipper.refresh_token_header_required',
    ErrorCodeEnum.shipper007: 'error_code.shipper.email_exists',
    ErrorCodeEnum.shipper008: 'error_code.shipper.phone_exists',
    ErrorCodeEnum.shipper009: 'error_code.shipper.phone_not_found',
    ErrorCodeEnum.shipper010: 'error_code.shipper.delivery_history_not_found',
    ErrorCodeEnum.shipper020:
        'error_code.shipper.not_reach_delivery_destination',
    ErrorCodeEnum.shipper022: 'error_code.shipper.shipper_not_arrived_hub',

    // STATISTICS
    ErrorCodeEnum.statistics001: 'error_code.statistics.shipper_id_required',
    ErrorCodeEnum.statistics002: 'error_code.statistics.period_type_required',
    ErrorCodeEnum.statistics003: 'error_code.statistics.invalid_start_date',

    // USER
    ErrorCodeEnum.user001: 'error_code.user.not_found',
    ErrorCodeEnum.user002: 'error_code.user.already_exists',
    ErrorCodeEnum.user003: 'error_code.user.invalid_phone',
    ErrorCodeEnum.user004: 'error_code.user.invalid_email_format',
    ErrorCodeEnum.user005: 'error_code.user.email_not_found',
    ErrorCodeEnum.user006: 'error_code.user.password_policy_violation',
    ErrorCodeEnum.user007: 'error_code.user.current_password_incorrect',
    ErrorCodeEnum.user008: 'error_code.user.sessions_not_found',
    ErrorCodeEnum.user009: 'error_code.user.email_exists',
    ErrorCodeEnum.user010: 'error_code.user.phone_exists',
    ErrorCodeEnum.user011: 'error_code.user.id_required',
    ErrorCodeEnum.user012: 'error_code.user.second_password_exists',
    ErrorCodeEnum.user013: 'error_code.user.second_password_incorrect',
    ErrorCodeEnum.user014: 'error_code.user.second_password_not_found',
    ErrorCodeEnum.user015: 'error_code.user.phone_not_belong',

    // PAYMENT CARD
    ErrorCodeEnum.paymentCard01: 'error_code.card.not_found',
    ErrorCodeEnum.paymentCard02: 'error_code.card.invalid_number',
    ErrorCodeEnum.paymentCard03: 'error_code.card.expired',
    ErrorCodeEnum.paymentCard04: 'error_code.card.not_supported',
    ErrorCodeEnum.paymentCard05: 'error_code.card.network_error',
    ErrorCodeEnum.paymentCard06: 'error_code.card.limit_exceeded',
    ErrorCodeEnum.paymentCard07: 'error_code.card.invalid_cvv',
    ErrorCodeEnum.paymentCard08: 'error_code.card.blocked',
    ErrorCodeEnum.paymentCard09: 'error_code.card.already_exists',

    // USER DOCUMENT
    ErrorCodeEnum.userDoc001: 'error_code.user_document.not_found',
    ErrorCodeEnum.userDoc002: 'error_code.user_document.already_exists',
    ErrorCodeEnum.userDoc003: 'error_code.user_document.invalid',
    ErrorCodeEnum.userDoc004: 'error_code.user_document.forbidden',
    ErrorCodeEnum.userDoc005: 'error_code.user_document.already_exists',

    // WALLET
    ErrorCodeEnum.wallet001: 'error_code.wallet.not_found',
    ErrorCodeEnum.wallet002: 'error_code.wallet.insufficient_balance',
    ErrorCodeEnum.wallet003: 'error_code.wallet.invalid_amount',
    ErrorCodeEnum.wallet004: 'error_code.wallet.already_exists',
    ErrorCodeEnum.wallet005: 'error_code.wallet.transaction_not_found',
    ErrorCodeEnum.wallet006: 'error_code.wallet.invalid_transaction_type',
    ErrorCodeEnum.wallet007: 'error_code.wallet.pending_withdraw_exists',

    ErrorCodeEnum.unknown: 'error_code.server_error',
  };

  /// raw backend code
  String get key => _mapKey[this]!;

  /// localization key
  String? get message => _mapValue[this];

  static String? getMessage(String? value) {
    if (value == null) return ErrorCodeEnum.unknown.message;
    return (_mapKey.entries.firstWhereOrNull((e) => e.value == value)?.key ??
            ErrorCodeEnum.unknown)
        .message;
  }
}
